services:
  postgres:
    container_name: carpultec-db
    image: postgres:17

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  carpultec:
    container_name: carpultec-app

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}  
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}

  osrm:
    container_name: osrm-backend
    image: osrm/osrm-backend:latest

    ports:
      - "5000:5000"

    volumes:
      - ./data:/data

    command: osrm-routed --algorithm mld /data/peru-260523.osrm

    restart: unless-stopped
volumes:
  postgres_data: