drop all objects;

create table users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null unique,
    phone varchar(255) unique,
    student_code varchar(255) unique,
    career varchar(255),
    cycle integer,
    rating double,
    profile_image_url varchar(1024),
    verified boolean not null
);

create table user_roles (
    user_id bigint not null,
    role varchar(255) not null,
    constraint fk_user_roles_user foreign key (user_id) references users (id)
);